### ISSUE TITLE
Git-Projects no longer finds my Git Projects...

### ISSUE THREAD

**Issue by DonkeyAfterDark** [prrrnd/atom-git-projects#16]
It worked fine on Friday, then I updated and blam... nothing found.

ATOM: https://www.dropbox.com/s/znnio88jzcd8smk/Screenshot%202015-03-16%2011.36.08.png?dl=0

CONSOLE: https://www.dropbox.com/s/qfsjfte277wkqsv/Screenshot%202015-03-16%2011.36.35.png?dl=0

**Comment by DonkeyAfterDark** [comment]
Reverting to this fixes the issue: https://raw.githubusercontent.com/prrrnd/atom-git-projects/f3cd7a1307d17ac68901aaf2a561287a02f792aa/lib/git-projects.coffee

**Comment by prrrnd** [comment]
Thanks for reporting your issue. 
Could you post the content of your `config.cson` file, which is located in your `.atom` directory?
Please make sure that your path is not being ignored with [this feature](https://github.com/prrrnd/atom-git-projects/pull/14)
Have you tried uninstalling and re-installing the package as well?

**Comment by DonkeyAfterDark** [comment]
1. I have tried uninstalling and re-installing the package.
2. I am ignoring some paths, but only in the fuzzy-finder array.
3. config.cson is below:

"*":
  "exception-reporting":
    userId: "bc24b7a3-adcc-a82d-c126-9098e6739f31"
  welcome:
    showOnStartup: false
  linter: {}
  core:
    themes: [
      "seti-ui"
      "seti-syntax"
    ]
    projectHome: "/Users/nkronemeyer/sharecare"
  editor:
    invisibles: {}
    fontSize: 14
    autoIndent: false
    scrollPastEnd: true
  "git-projects":
    rootPath: "/Users/nkronemeyer/git"
    openInDevMode: true
  "fuzzy-finder":
    ignoredNames: [
      "*.txt"
      ".git*"
      "Gemfile*"
      "README*"
      "*README"
      ".project"
      "*.sh"
      "*.xml"
      "*.rb"
      "*.json"
      "*.properties"
      "*cfg*"
      "*.example"
      "*.pdf"
      "*.png"
      "*.types"
    ]

**Comment by davidschou** [comment]
i'm having the issue also.  here is my config.cson
```
$ cat config.cson
"*":
  editor:
    softTabs: false
    scrollPastEnd: true
    invisibles: {}
    fontSize: 14
  core:
    themes: [
      "atom-dark-ui"
      "atom-dark-syntax"
    ]
  linter: {}
  "exception-reporting":
    userId: "f0c4d091-8112-1ff9-5056-538039e6d16e"
  welcome:
    showOnStartup: false
  "tree-view": {}
  minimap: {}
  "atom-terminal":
    app: "iTerm.app"
  "spell-check": {}
  "autocomplete-plus": {}
  "project-ring": {}
  "git-projects":
    showSubRepos: true
    rootPath: "/Users/davidc397/git; /Users/davidc397/out/git"
    sortBy: "Latest modification date"
```

**Comment by prrrnd** [comment]
Alright, I believe I figured it out. Both of you have a `rootPath` containing the string `"git"`, which is also contained in the default ignored path. I updated the default ignored path from `node_modules;.git` to `node_modules;\\.git`. The fix should be available today in the 1.10.1 release.

**Comment by davidschou** [comment]
:+1:

**Comment by DonkeyAfterDark** [comment]
That fixed it for me. Thanks.
