### ISSUE TITLE
Unclear meaning of some settings

### ISSUE THREAD

**Issue by laughedelic** [prrrnd/atom-git-projects#23]
Hi! It's a nice plugin, but I have a couple of questions about settings that are unclear for me from the readme:

- what are notifications? 
- what is "open in development mode"?
- root paths vs. ignored paths: how does it search for repos? if it found something, will it continue searching inside? (is the `showSubRepos` setting related? it's not listed in the settings UI btw)

**Comment by prrrnd** [comment]
Hi, thanks for the feedback.

- A notification appears when a new version is available, and you can turn that off.
- Running in development mode will load packages from `~/.atom/dev/packages` as well as `~/.atom/packages`, it is mostly used by developers to test what they are working on.
- Root paths: All the paths where git projects will try to find repositories from, separated by a semicolon.
Some paths can be ignored by either an "ignored path" or an "ignored pattern"
- `showSubRepos` has been removed, I need to update the README.

**Comment by prrrnd** [comment]
I have removed the `showSubRepos` setting from the README.

**Comment by laughedelic** [comment]
Hi @prrrnd. Thank for the answer.
- why do you need notifications about new versions if it's done by Atom anyway?
- I think that the development mode shouldn't be exposed to the user (how other plugins do it?)
- my question was mostly this: if it found something, will it continue searching inside? (it just runs for too long)
