### ISSUE TITLE
Package could not be loaded because it contains native modules that aren't compatible Atom >= 0.196.0.

### ISSUE THREAD

**Issue by cassianoleal** [prrrnd/atom-git-projects#26]
I got this warning using `git-projects` 1.13.0 on Atom 0.196.0:

---

The following packages could not be loaded because they contain native modules that aren't compatible with this version of Atom.

Previous Atom versions shipped with Chrome 31 and Node 0.11.10 but Atom now ships with Chrome 41.0.2272.76 and Node 1.5.1.

The packages listed should now ship versions of these native modules that are compatible with Node 1.5.1.

Updates for these packages may already be available that resolve this issue.

If no update is available you may want to notify the package author that their package isn't supported in Atom 0.196.0 because of the Chrome 41.0.2272.76 and Node 1.5.1 upgrade.

If you think a package is listed here and should no longer be, click the button below to reload Atom and recheck all packages.

### Git Projects 1.13.0
Listed below are the incompatible native modules that this package depends on.

* git-utils@3.0.0
Error message: Module version mismatch. Expected 43, got 41.

**Comment by prrrnd** [comment]
Hi, thanks for your input.
I have had the same issue and reported it to git-utils. I have been able to somehow fix this by reinstalling git projects.

**Comment by cassianoleal** [comment]
I see. I only saw it this once when I reported the error. Feel free to close this if it's not an issue with this package directly.
Thanks!
