### ISSUE TITLE
Looking for repositories takes forever

### ISSUE THREAD

**Issue by varemenos** [prrrnd/atom-git-projects#36]
Is there a reason why this could happen? The devtools show no logs about it.

**Comment by prrrnd** [comment]
Can you give more details? Forever, as in not working at all or does it take a long time? How long? Also, what are your root paths/what is your config?

**Comment by varemenos** [comment]
It takes about 10 minutes to index and my config is the default one. The issue might be because my repos directory is a bit on the heavy side. Does this plugin index recursively everything inside `~/repos`? If yes, would you consider adding a checkbox to disable this recursive behaviour and only index top-level directories inside `~/repos`?

**Comment by prrrnd** [comment]
Yes, it does index recursively. Wouldn't playing with the `maxDepth` option help you achieve that?

**Comment by varemenos** [comment]
Ohh, I'm terribly sorry, I didn't realise there was already an option for it
