### ISSUE TITLE
Remove check for updates and jQuery

### ISSUE THREAD

**Issue by varemenos** [prrrnd/atom-git-projects#42]
Why are you [checking for updates](https://github.com/prrrnd/atom-git-projects/blob/master/lib/git-projects.coffee#L61-L73), atom does it anyway

**Comment by prrrnd** [comment]
Hi,
Yes, Atom does this. I just wanted to show a notification as I tend not to look at the bottom right corner and miss updates.
I am going to remove this feature and jQuery as it only depends on this :+1:

**Comment by prrrnd** [comment]
Resolved in https://github.com/prrrnd/atom-git-projects/commit/92eb61734c38b5c11e69a302b8ec3507317a2bf3.

**Comment by varemenos** [comment]
Great, thanks :)
