### ISSUE TITLE
change project within current window

### ISSUE THREAD

**Issue by stephanfriedrich** [prrrnd/atom-git-projects#5]
hy Pierre,
i like your package, but currently after changing a atom-project, it opens a new window. 
it would be nice, if it opens the new project in the current window.

what do you think?

**Comment by prrrnd** [comment]
Hi, and thank you.
I am going to look into this. I know there are some issues about this though. See [#5138](https://github.com/atom/atom/issues/5138) in [atom/atom](https://github.com/atom/atom/) for instance

**Comment by jnunemaker** [comment]
I'd love this as well. Always missed this after switching from sublime to atom.

**Comment by cyanpunk** [comment]
:+1: Awesome idea.

**Comment by ekonstantinidis** [comment]
I couldn't agree more with what @cyanpunk said. I'd prefer `add as folder in current window` but having those 3 options will make 100% complete for me!

**Comment by jcurtis** [comment]
Came here looking for exactly this. +1 to @cyanpunk's suggestion.

**Comment by jcurtis** [comment]
Implemented add to current window with #53

**Comment by prrrnd** [comment]
Resolved in 1.17.0, released today.

**Comment by stephanfriedrich** [comment]
nice ... thx :)
