### ISSUE TITLE
ctrl+alt+o does'nt work in 1.15.0

### ISSUE THREAD

**Issue by ransingh** [prrrnd/atom-git-projects#50]
invocation of git-projects using shortcut 'ctrl + alt + o' just stopped working in v1.15.0.
It was working before. I tried putting in different key combination but that did  not work either.

I am using Atom v1.0.13.

I am using the following plugins as well. 
![screen shot 2015-09-21 at 9 32 50 am](https://cloud.githubusercontent.com/assets/490083/9983562/d8868dec-6043-11e5-889b-52dbe4388611.png)

**Comment by igreg** [comment]
I had a similar issue and had to recompile a module within git-projects that was compiled for an old version of Atom. It didn't work at first, but after re-installing the plugin and trying again, it finally worked and the shortcut started to work again.

It is easy to know if you have the same issue than me. You will see a red bug with a number in the bottom right corner which you can click on, and it should be fairly obvious what to do next.

Hope this helps!

**Comment by legomind** [comment]
Just wanted to back up @igreg on this. For me it was just as he described. After rebuilding git-utils, everything works fine.

**Comment by ransingh** [comment]
Cool I will give it go. Sent from Yahoo7 Mail  for iPhoneOn 25 Sep 2015, 10:08:19 AM, legomind wrote:Just wanted to back up @igreg on this. For me it was just as he described. After rebuilding git-utils, everything works fine.

**Comment by prrrnd** [comment]
Thank you for reporting the issue.
I looked into it, and realised that Atom provides an easy way to rebuild packages when necessary.
I close this one.
