### ISSUE TITLE
feature request: cache results

### ISSUE THREAD

**Issue by mark-hahn** [prrrnd/atom-git-projects#6]
I have about 50 projects to open and it takes around 10 seconds which isn't a big deal but a bit annoying.

I know others probably wouldn't benefit so I will do a PR when I get a chance.

**Comment by prrrnd** [comment]
Great, thanks! I've also been thinking about using the async methods instead of how it is right now. It blocks the UI during those 10 seconds, right?

**Comment by mark-hahn** [comment]
Yes it blocks.  But I can't imagine doing anything else while waiting.  The
best solution is to never wait.  (grin)

The cache could be kept up-to-date in the background and used when needed.
So only the cache stuff would need to be async.  Actually at this point it
isn't a cache.  It is the real data.

I'd do this as much for fun as for need.

**Comment by prrrnd** [comment]
Keeping the projects list up to date in the background by "listening" to the directories in the `rootPath` sounds like the best possible solution. It would be great if you could come up with a pull request for that! Feel free to assign the issue to yourself if you want to :-)

**Comment by mark-hahn** [comment]
I can't assign myself. You will need to.

**Comment by prrrnd** [comment]
Hm, i'm on mobile at the moment. I'll do that when I get back on my computer.

**Comment by mark-hahn** [comment]
I don't think there are so many issues that assigning owners to issues is
that important.  (grin)

**Comment by mark-hahn** [comment]
FYI: I've started on caching.  It is probably going to be a lot of code.

**Comment by prrrnd** [comment]
You're right about assigning people to issues. Just thought it would be good to keep things in order. I too have OCDs ;-) 
Looking forward to your PR then, let me know if I can help somehow. I'm quite busy this week though.

**Comment by mark-hahn** [comment]
I'm not going to do this because I found a major speedup.  I will submit a new issue.
