### ISSUE TITLE
feature request: Add option to include folders with package.json

### ISSUE THREAD

**Issue by mark-hahn** [prrrnd/atom-git-projects#7]
I'd like to put virtually anything that smells like a project folder in the list.  Right now that means including folders with package.json but I might even come up with better ideas.

I will need to do the other cache feature first or my load time will get ridiculous.

If you haven't noticed, I use `git-projects` all the time.  Simple idea but it really works for me.  I used to use one that required me to keep an edited list up-to-date but that was a PITA.

**Comment by mark-hahn** [comment]
P.S. See https://discuss.atom.io/t/shout-out-for-git-projects/15202

**Comment by prrrnd** [comment]
Thanks for the shout out! 
I think we used to use the same package, and keeping the list of projects updated was really annoying. That's why I decided to create `git-projects`. Now I'm not sure I understand this request. You would like to be able to list other projects than the ones containing a `.git`? That seems like a good idea, but I think it would be kind of out of scope.

**Comment by mark-hahn** [comment]
>  You would like to be able to list other projects than the ones containing a .git? 

I admit I don't have many projects that aren't on git.  If I know there will never be a remote repo then I only use git for archiving,  I think I will have more git-less projects now that I use live-archive for archiving.

>  I think it would be kind of out of scope.

I have noticed that our use cases are a bit different. The first symptom was wanting multiple root folders.  The second was wanting to open always in dev mode.  Now I see some new diffs.  E.G.the cache isn't needed for a normal number of projects so that's another diff. It will be bloating things a bit and there will be a trade-off of speed when bringing it up versus slowness the rest of the time like load time.

I've given thoughts to a fork..  

Cons ....

- It would split the user base
- It would confuse users because it would be hard to tell which to use.
- I would feel guilty for stealing your code
- We wouldn't have the synergy of bouncing ideas
- we would have duplication of efforts

Pros ...

- I could use my coding style (it's a pain to remember to use yours)
- There would be fewer confusing settings for users.
- I could customize it more to my liking. 
- It would help assuage my OCD
- Would have more project count to brag about (grin)
- I wouldn't pressure you to do it my way (I get pushy)

Of course you would get prominent credit.  I can't decide. It;s a toss-up.  I will leave the decision totally up to you.

**Comment by mark-hahn** [comment]
> Thanks for the shout out! 

Aarrggh.  I accidentally had a link to one of my projects instead of your.  I just fixed it.

**Comment by mark-hahn** [comment]
I have no plans to do a PR in the near future.
